[project]
name = "approvaltests-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.1",
    "typing-extensions>=4.14.1",
]
