name: Claude Date Scrubber Enhancement
on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

jobs:
  claude-date-scrubber:
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.labels && contains(github.event.issue.labels.*.name, 'date-scrubber')) ||
      (github.event.comment && github.event.issue.labels && contains(github.event.issue.labels.*.name, 'date-scrubber') && contains(github.event.comment.body, '@claude'))
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          custom_instructions: |
            You are working on extending DateScrubber.get_scrubber_for() to support additional date formats.
            
            First, use `gh issue view ${{ github.event.issue.number }} --comments` to see the specific date formats that need to be supported.
            
            For reference, examine PR #206 from the upstream repository which shows an example of adding date format support:
            Use `gh pr view 206 --repo approvals/ApprovalTests.Python` to see the implementation approach.
          allowed_tools: |
            Bash
          trigger_phrase: "@claude"